# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Data schemas for the Hyper-Personalized Shopping Squad.
Defines the structured communication protocol between the Planner, Scouts, 
Evaluator, and Negotiator agents using Pydantic models.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class ShoppingComponent(BaseModel):
    """
    Represents a single category within a larger shopping request.
    Example: 'Tent' or 'Vintage Flannel Shirt'.
    """
    category: str = Field(..., description="The type of item to search for")
    budget_allocation: float = Field(..., description="Maximum price in USD for this specific item")
    description_prompt: str = Field(..., description="Keywords or aesthetic 'vibes' to guide the Scout's vector search")

class ShoppingPlan(BaseModel):
    """
    The master blueprint generated by the Planner Agent.
    Contains the breakdown of the user's vague request into actionable components.
    """
    theme: str = Field(..., description="The overarching theme (e.g., '90s Grunge' or 'Ultralight Backpacking')")
    total_budget: float = Field(..., description="The user's maximum spend for the entire bundle")
    components: List[ShoppingComponent] = Field(..., description="List of items required to fulfill the request")
    reasoning: str = Field(..., description="Detailed paragraph explaining the style choices and occasion fit")

class CartItem(BaseModel):
    """
    A specific product found by a Scout Agent via the Vector Search Backend.
    """
    id: str = Field(..., description="Unique product ID from the Mercari dataset")
    name: str = Field(..., description="Title of the product listing")
    price: float = Field(..., description="The product's price in USD")
    img_url: str = Field(..., description="Direct link to the product image")
    url: str = Field(..., description="Link to the original product listing")
    description: str = Field(..., description="Full text description of the product")
    similarity: float = Field(0.0, description="The semantic relevance score returned by the Vector Search (0.0 to 1.0)")

class CartItemOptions(BaseModel):
    """
    A collection of different product options found by a Scout Agent for a single category.
    """
    category: str = Field(..., description="The category these items belong to")
    options: List[CartItem] = Field(..., description="A list of at least 3 distinct items that match the user's criteria")

class EvaluationReport(BaseModel):
    """
    The gatekeeper's report. Used by the workflow loop to determine if the 
    current bundle is valid or needs re-planning.
    """
    is_valid: bool = Field(..., description="True if the bundle meets budget and theme constraints")
    feedback: Optional[str] = Field(None, description="Detailed instructions for the Planner if a retry is needed")
    total_cost: float = Field(..., description="The sum of all prices for items currently in the cart")

class ShoppingBundle(BaseModel):
    """
    The final output of the squad. A cohesive 'kit' ready for the Negotiator.
    """
    items: List[CartItem] = Field(..., description="The collection of items selected for the user")
    total_price: float = Field(..., description="Final combined cost of the bundle")
    theme_consistency_score: float = Field(..., description="An aggregate score of how well the items match the requested theme")