import asyncio
import os
import click
import uvicorn
from dotenv import load_dotenv

# --- A2A Server Imports ---
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.apps import A2AStarletteApplication
from a2a.server.events import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore, TaskUpdater
from a2a.types import (AgentCapabilities, AgentCard, AgentSkill, InternalError,
                       InvalidParamsError, Part, TextPart,
                       UnsupportedOperationError)
from a2a.utils import new_task
from a2a.utils.errors import ServerError

# --- LangGraph Imports ---
from graph import build_planner_graph
from state import PlanState

load_dotenv()

class PlannerAgentExecutor(AgentExecutor):
    """
    An AgentExecutor that runs the LangGraph Planner.
    It receives an A2A task, passes the query as the 'objective' into LangGraph,
    and returns the final report generated by the graph.
    """

    SUPPORTED_CONTENT_TYPES = ["text", "text/plain"]

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        # Extract the incoming objective from another agent
        objective = context.get_user_input()
        if not objective:
            raise ServerError(error=InvalidParamsError("User query (objective) cannot be empty."))

        # Initialize tracking task
        task = context.current_task or new_task(context.message)
        await event_queue.enqueue_event(task)
        updater = TaskUpdater(event_queue, task.id, task.context_id)

        try:
            print(f"\n🚀 [A2A Executor] Triggering LangGraph with objective: '{objective}'")
            
            # 1. Build the LangGraph workflow
            graph = build_planner_graph()
            
            # 2. Set the initial state
            initial_state: PlanState = {"objective": objective}
            
            # 3. Execute the graph asynchronously
            # (LangGraph's ainvoke automatically handles sync nodes by running them in threads)
            final_state = await graph.ainvoke(initial_state)
            
            # 4. Extract the final report
            # Depending on how it's returned, it might be in the root state or nested under the node name
            final_report = "Execution completed, but no report was generated."
            if "final_report" in final_state:
                final_report = final_state["final_report"]
            elif "generate_report" in final_state and "final_report" in final_state["generate_report"]:
                final_report = final_state["generate_report"]["final_report"]

            print(f"\n✅ [A2A Executor] LangGraph finished. Report preview: '{final_report[:100]}...'")
            
            # 5. Send the result back to the calling agent
            await updater.add_artifact([Part(root=TextPart(text=final_report))], name="orchestration_report")
            await updater.complete()

        except Exception as e:
            print(f"❌ [A2A Executor] Error occurred during execution: {e}")
            await updater.fail()
            raise ServerError(error=InternalError(str(e))) from e

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise ServerError(error=UnsupportedOperationError())


@click.command()
def main():
    """Starts the LangGraph Planner A2A server."""
    host = "0.0.0.0"
    port = int(os.environ.get("PORT", 8080))
    public_url = os.environ.get("PLANNER_AGENT_URL", f"http://localhost:{port}/")

    async def start_server():
        print("Defining Agent Card for the Global Retail IT Orchestrator...")
        
        agent_card = AgentCard(
            name="Retail-Orchestrator-A2A",
            description="A high-level LangGraph planner agent that delegates logistics and inventory tasks to a CrewAI execution swarm.",
            url=public_url,
            version="1.0.0",
            default_input_modes=PlannerAgentExecutor.SUPPORTED_CONTENT_TYPES,
            default_output_modes=PlannerAgentExecutor.SUPPORTED_CONTENT_TYPES,
            capabilities=AgentCapabilities(streaming=False),
            skills=[
                AgentSkill(
                    id="orchestrate_logistics",
                    name="Orchestrate Logistics",
                    description="Analyzes inventory alerts and orchestrates a multi-agent workflow to procure and manage retail stock.",
                    tags=["logistics", "retail", "orchestration", "planning", "procurement"],
                    examples=[
                        "Inventory Alert: Northeast Region is critically low on 'Rare Japanese Anime Figure'. Please order 2 units ASAP. Max budget $50 per unit."
                    ],
                )
            ],
        )

        try:
            # Wire up the server components
            agent_executor = PlannerAgentExecutor()
            request_handler = DefaultRequestHandler(agent_executor=agent_executor, task_store=InMemoryTaskStore())
            server = A2AStarletteApplication(agent_card=agent_card, http_handler=request_handler)
            
            print(f"Starting A2A Server at {public_url}")
            config = uvicorn.Config(server.build(), host=host, port=port)
            server_instance = uvicorn.Server(config)
            await server_instance.serve()
        except Exception as e:
            print(f"Failed to start server: {e}")

    asyncio.run(start_server())

if __name__ == "__main__":
    main()
