steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.control-room
      - -t
      - $_IMAGE_URI
      - --build-arg
      - UV_EXTRA_INDEX_URL=$_UV_EXTRA_INDEX_URL
      - .

images:
  - $_IMAGE_URI
