import asyncio
import json
import os
import sys
import click
import uvicorn
from dotenv import load_dotenv
import vertexai

# Ensure the 02-scale/ directory is on sys.path so `from agents.xxx` imports work
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

# A2A Server Imports
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.apps import A2AStarletteApplication
from a2a.server.events import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore, TaskUpdater
from a2a.types import (AgentCapabilities, AgentCard, AgentSkill, InternalError,
                       InvalidParamsError, Part, TextPart,
                       UnsupportedOperationError)
from a2a.utils import new_task
from a2a.utils.errors import ServerError

# LangGraph Imports
load_dotenv()


def _build_planner_agent_engine():
    """Return the deployed planning Agent Engine handle if configured."""
    planning_engine_id = os.environ.get("PLANNING_AGENT_ENGINE_ID", "").strip()
    if not planning_engine_id:
        return None

    project = os.environ.get("GOOGLE_CLOUD_PROJECT", "").strip()
    location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1").strip()
    if not project:
        raise RuntimeError(
            "GOOGLE_CLOUD_PROJECT is required when PLANNING_AGENT_ENGINE_ID is set."
        )

    client = vertexai.Client(project=project, location=location)
    return client.agent_engines.get(name=planning_engine_id)


class PlannerAgentExecutor(AgentExecutor):
    """
    An AgentExecutor that runs the LangGraph Planner.
    It receives an A2A task, passes the query as the 'objective' into LangGraph,
    and returns the final report generated by the graph.
    """

    SUPPORTED_CONTENT_TYPES = ["text", "text/plain"]

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        # Extract the incoming objective from another agent
        objective = context.get_user_input()
        if not objective:
            raise ServerError(error=InvalidParamsError(message="User query (objective) cannot be empty."))

        # Initialize tracking task
        task = context.current_task or new_task(context.message)
        await event_queue.enqueue_event(task)
        updater = TaskUpdater(event_queue, task.id, task.context_id)

        try:
            print(f"\n🚀 [A2A Executor] Triggering LangGraph with objective: '{objective}'")
            # Push directly to dashboard — A2A message/send doesn't stream artifacts
            from agents.planner.graph import _push_to_dashboard
            _push_to_dashboard("Setting up the LangGraph planning workflow...", "system")
            await updater.add_artifact(
                [Part(root=TextPart(text="Setting up the LangGraph planning workflow..."))],
                name="planner_step",
            )

            planner_engine = _build_planner_agent_engine()
            if planner_engine is not None:
                _push_to_dashboard("Delegating to the cloud-hosted Planning Agent on Agent Engine...", "system")
                await updater.add_artifact(
                    [Part(root=TextPart(text="Delegating to the cloud-hosted Planning Agent on Agent Engine..."))],
                    name="planner_step",
                )
                final_report = await asyncio.to_thread(planner_engine.query, input=objective)
                _push_to_dashboard("Cloud-hosted Planning Agent completed.", "system")
                await updater.add_artifact(
                    [Part(root=TextPart(text="Cloud-hosted Planning Agent completed."))],
                    name="planner_step",
                )
                await updater.add_artifact(
                    [Part(root=TextPart(text=str(final_report)))],
                    name="orchestration_report",
                )
                await updater.complete()
                return
            
            # Define an update callback to stream artifacts during graph execution
            async def on_graph_update(msg: str):
                await updater.add_artifact([Part(root=TextPart(text=msg))], name="planner_step")

            # 1. Build the LangGraph workflow with the callback
            from agents.planner.graph import build_planner_graph
            from agents.planner.state import PlanState
            graph = build_planner_graph(on_update=on_graph_update)
            
            # 2. Set the initial state
            initial_state: PlanState = {"objective": objective}
            
            # 3. Execute the graph asynchronously with streaming
            _push_to_dashboard("Planning workflow ready. Starting execution...", "system")
            await on_graph_update("Planning workflow ready. Starting execution...")
            final_report = "Execution completed, but no report was generated."
            async for step in graph.astream(initial_state):
                # Each 'step' is a dict of {node_name: state_delta}
                for node_name, state in step.items():
                    print(f"  [Planner] Node '{node_name}' finished.")
                    
                    # Also send a node completion artifact
                    await on_graph_update(f"Completed stage: {node_name}")
                    
                    # Update final report if it appears in the delta
                    if "final_report" in state and state["final_report"]:
                        final_report = state["final_report"]

            print(f"\n✅ [A2A Executor] LangGraph finished. Report preview: '{final_report[:100]}...'")
            
            # 5. Send the final result back to the calling agent
            await updater.add_artifact([Part(root=TextPart(text=final_report))], name="orchestration_report")
            await updater.complete()

        except Exception as e:
            print(f"❌ [A2A Executor] Error occurred during execution: {e}")
            await updater.failed()
            raise ServerError(error=InternalError(message=str(e))) from e

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise ServerError(error=UnsupportedOperationError())


@click.command()
def main():
    """Starts the LangGraph Planner A2A server."""
    host = "0.0.0.0"
    port = int(os.environ.get("PORT", 8080))
    public_url = os.environ.get("PLANNER_AGENT_URL", f"http://localhost:{port}/")

    async def start_server():
        print("Defining Agent Card for the Global Retail IT Orchestrator...")
        
        agent_card = AgentCard(
            name="Retail-Orchestrator-A2A",
            description="A high-level LangGraph planner agent that delegates logistics and inventory tasks to a CrewAI execution swarm.",
            url=public_url,
            version="1.0.0",
            default_input_modes=PlannerAgentExecutor.SUPPORTED_CONTENT_TYPES,
            default_output_modes=PlannerAgentExecutor.SUPPORTED_CONTENT_TYPES,
            capabilities=AgentCapabilities(streaming=True),
            skills=[
                AgentSkill(
                    id="orchestrate_logistics",
                    name="Orchestrate Logistics",
                    description="Analyzes inventory alerts and orchestrates a multi-agent workflow to procure and manage retail stock.",
                    tags=["logistics", "retail", "orchestration", "planning", "procurement"],
                    examples=[
                        "Inventory Alert: Northeast Region is critically low on 'Rare Japanese Anime Figure'. Please order 2 units ASAP. Max budget $50 per unit."
                    ],
                )
            ],
        )

        try:
            # Wire up the server components
            agent_executor = PlannerAgentExecutor()
            request_handler = DefaultRequestHandler(agent_executor=agent_executor, task_store=InMemoryTaskStore())
            server = A2AStarletteApplication(agent_card=agent_card, http_handler=request_handler)
            
            print(f"Starting A2A Server at {public_url}")
            config = uvicorn.Config(server.build(), host=host, port=port)
            server_instance = uvicorn.Server(config)
            await server_instance.serve()
        except Exception as e:
            print(f"Failed to start server: {e}")

    asyncio.run(start_server())

if __name__ == "__main__":
    main()
